<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Auth\" />
      <Folder Include="Helix\Moderation\" />
      <Folder Include="Helix\Polls\" />
      <Folder Include="Helix\Predictions\" />
      <Folder Include="Helix\Raids\" />
      <Folder Include="Helix\Schedule\" />
      <Folder Include="Helix\Search\" />
      <Folder Include="Helix\Streams\" />
      <Folder Include="Helix\Subscriptions\" />
      <Folder Include="Helix\Tags\" />
      <Folder Include="Helix\Teams\" />
      <Folder Include="Helix\Users\" />
      <Folder Include="Helix\Videos\" />
    </ItemGroup>

</Project>
